Added gradle test report

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -31,11 +31,16 @@ jobs:
           run: ./gradlew checkstyleMain checkstyleTest checkstyleIntegrationTest
         - name: Running Spotbugs
           run: ./gradlew spotbugsMain spotbugsTest spotbugsIntegrationTest
-        - name: Publish Test Report
+        - name: Publish Unit Test Report
           uses: mikepenz/action-junit-report@v4
           if: success() || failure() # always run even if the previous step fails
           with:
             report_paths: '**/build/test-results/test/TEST-*.xml'
+        - name: Publish Integration Test Report
+          uses: mikepenz/action-junit-report@v4
+          if: success() || failure() # always run even if the previous step fails
+          with:
+            report_paths: '**/build/test-results/integrationTest/TEST-*.xml'
 
 #        - name: Upload Build Reports
 #          uses: actions/upload-artifact@v3
